Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "strawberry")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Tekila")
Ingredient.create(name: "Whisky")
